# Generated by Django 4.2.6 on 2023-11-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paleta',
        ),
    ]
