# Generated by Django 4.2.6 on 2023-11-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_marca_blog_autor_rename_modelo_blog_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
