# Generated by Django 4.2.6 on 2023-12-15 23:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descripcion',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
