# Generated by Django 4.2.6 on 2023-11-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovil', '0002_rename_auto_automovil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Automovil',
            new_name='Blog',
        ),
    ]
