# Generated by Django 4.2.6 on 2023-11-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovil', '0003_rename_automovil_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='marca',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='modelo',
            new_name='titulo',
        ),
    ]
